#!/usr/bin/env python3

from json import dump
from pathlib import Path
from subprocess import Popen
import os


def getenv(name):
    if name in os.environ:
        return os.environ[name]
    else:
        return ""

user = "{}".format(Path.home())
user_json_dir ="{}/.config/pardus/pardus-special-theme".format(user)
user_json_file = "{}/special-theme.json".format(user_json_dir)

dic = {}

dic["light"] = {}
dic["dark"] = {}

dic["light"]["name"] = "pardus-@@desktop@@-yuzyil"
dic["light"]["pretty_tr"] = "100. Yıl Açık"
dic["light"]["pretty_en"] = "100th Year Light"
dic["light"]["background"] = "/usr/share/backgrounds/pardus-yuzyil.webp"
dic["light"]["image"] = "/usr/share/pardus/pardus-yuzyil/theme-light.png"

dic["dark"]["name"] = "pardus-@@desktop@@-yuzyil-dark"
dic["dark"]["pretty_tr"] = "100. Yıl Koyu"
dic["dark"]["pretty_en"] = "100th Year Dark"
dic["dark"]["background"] = "/usr/share/backgrounds/pardus-yuzyil.webp"
dic["dark"]["image"] = "/usr/share/pardus/pardus-yuzyil/theme-dark.png"

Path(user_json_dir).mkdir(parents=True, exist_ok=True)

jsondump_file = open(user_json_file, "w", encoding='utf8')
dump(dic, jsondump_file, ensure_ascii=False, indent=2)
jsondump_file.flush()
jsondump_file.close()


if "xfce" in getenv("XDG_CURRENT_DESKTOP").lower() or "xfce" in getenv("XDG_SESSION_DESKTOP").lower() or "xfce" in getenv("DESKTOP_SESSION").lower():
    Popen(["/usr/bin/pardus-xfce-greeter", "--page", "1"])
elif "gnome" in getenv("XDG_CURRENT_DESKTOP").lower() or "gnome" in getenv("XDG_SESSION_DESKTOP").lower() or "gnome" in getenv("DESKTOP_SESSION").lower():
    Popen(["/usr/bin/pardus-gnome-greeter", "--page", "2"])
else:
    print("Your desktop environment not supported.")
    print(getenv("XDG_CURRENT_DESKTOP").lower())
    print(getenv("XDG_SESSION_DESKTOP").lower())
    print(getenv("DESKTOP_SESSION").lower())
